# Generated by Django 6.0.6 on 2026-08-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
